# this is name of the workflow that will be displayed in the Actions Tab

name: My first workflow

# Manual click (deliver) workflow whenever user needs

on:
    workflow_dispatch:
      inputs:
        environment:
         description: This is the environment where index.html will get deployed
         default: 'dev'
         required: true
         type: choice
         options:
          - dev
          - prod
          - stage

jobs:

  code:

    runs-on: ubuntu-latest

    steps:

      - name: checkout code

        run: echo "COde Clone from GitHub"

  build:
    needs: [code]
    runs-on: ubuntu-latest

    steps:
      
      - name: Build Docker Container

        run: echo "Docker Container build"

  test:
    needs: [build]
    runs-on: ubuntu-latest

    steps:

      - name: Test the container

        run: echo "Testing the container"

        

  deploy:
    if: inputs.environment=='dev'

    runs-on: ubuntu-latest

    steps:

      - name: Deploying the app

        run: echo "Docker compose deployed the app"
