name: python-lint

on:
  push:
    branches: main

jobs:
  validation:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9, 3.10, 3.11]
    
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: dockerhub login
        uses: docker/login-action@v4
        with:
          username: ${{vars.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PASS}}

      - name: docker build & push
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ${{vars.DOCKERHUB_USER}}/github-action-app:latest